# Generated by Django 6.0 on 2025-12-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovedone',
            name='is_alerted',
            field=models.BooleanField(default=False, help_text='Whether this loved one should be alerted when crash is detected'),
        ),
    ]
