# Generated by Django 6.0 on 2025-12-17 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('crash_timestamp', models.DateTimeField()),
                ('is_confirmed_crash', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('crash_type', models.CharField(blank=True, max_length=255)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('key_indicators', models.JSONField(blank=True, default=list)),
                ('false_positive_risk', models.FloatField(blank=True, null=True)),
                ('max_g_force', models.FloatField(blank=True, null=True)),
                ('impact_acceleration', models.JSONField(blank=True, default=dict)),
                ('final_tilt', models.JSONField(blank=True, default=dict)),
                ('alert_sent', models.BooleanField(default=False)),
                ('user_feedback', models.CharField(blank=True, choices=[('true_positive', 'True Positive'), ('false_positive', 'False Positive')], max_length=20)),
                ('user_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crash Event',
                'verbose_name_plural': 'Crash Events',
                'ordering': ['-crash_timestamp'],
                'indexes': [models.Index(fields=['device_id', '-crash_timestamp'], name='device_cras_device__f4a1c9_idx'), models.Index(fields=['is_confirmed_crash', '-crash_timestamp'], name='device_cras_is_conf_dcc70f_idx'), models.Index(fields=['user', '-crash_timestamp'], name='device_cras_user_id_aaffca_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('fcm_token', models.CharField(max_length=500)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_id'], name='device_devi_device__ac8116_idx'), models.Index(fields=['user', 'is_active'], name='device_devi_user_id_0dc297_idx'), models.Index(fields=['fcm_token'], name='device_devi_fcm_tok_1b2719_idx')],
                'unique_together': {('device_id', 'fcm_token')},
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('ax', models.FloatField()),
                ('ay', models.FloatField()),
                ('az', models.FloatField()),
                ('roll', models.FloatField()),
                ('pitch', models.FloatField()),
                ('tilt_detected', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device_id', '-timestamp'], name='device_sens_device__3e8b68_idx')],
            },
        ),
    ]
