# Generated by Django 6.0 on 2025-12-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashevent',
            name='crash_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crashevent',
            name='crash_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crashevent',
            name='crash_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crashevent',
            name='gps_fix_at_crash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crashevent',
            name='satellites_at_crash',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
